### ISSUE TITLE
引入组件不生效

### ISSUE THREAD

**Issue by shijunwen** [IronLu233/ant-design-remax#2]
`import { CheckboxGroup as WechatCheckboxGroup } from "remax/wechat";
import { CheckboxGroup as AliPayCheckboxGroup } from "remax/ali";
import { CheckboxGroup as ToutiaoCheckboxGroup } from "remax/toutiao";

const current = {
  alipay: AliPayCheckboxGroup,
  toutiao: ToutiaoCheckboxGroup,
  wechat: WechatCheckboxGroup
}[process.env.REMAX_PLATFORM! as "alipay" | "toutiao" | "wechat"] as
  | typeof WechatCheckboxGroup
  | typeof AliPayCheckboxGroup
  | typeof ToutiaoCheckboxGroup;

export default current;`

import NaiveCheckboxGroup from "@/components/universe/CheckboxGroup";
这样写，组件没生效。但是我直接从remax/wechat 是没有问题的。请问你存在这个问题吗

**Comment by IronLu233** [comment]
这个项目我还没写完。很多地方还没测试。Remax升级2.0之后也没升级。十分抱歉给您带来困扰
